### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by gurmukhp** [cold-logic/heos-controller-electron#1]
Awesome tool! Would it be possible to implement toggling the Night Mode for the Home Cinema?

**Comment by cold-logic** [comment]
Thank you Gurmukh! I'd love to add that in. Unfortunately I don't have a home cinema speaker myself and the network calls I'd need to enable night mode aren't documented in their API. If you really want this, you can send me a wireshark packet capture of the tcp traffic between the app and your home cinema... That might give me enough info to build out the feature for you.

**Comment by emidiez** [comment]
@cold-logic, this is great. I have 11 HEOS at home and seeking to control them over SIRI so I don't need to replace them with the HomeHubs that are expensive.
I have seen 2 options, one with HomeBridge and another with IFTTT tricks, but none of them is OTB and will need some work.
Are you interested in collaborating on that project?

**Comment by cold-logic** [comment]
Hi @emidiez! Sounds like you're a HEOS geek too! Eleven speakers... That must be amazing. I personally don't use Siri too much but HomeBridge looks like it might be perfect for the job. I don't have enough time at the moment to devote toward spearheading that kind of effort but I'd be happy to look over code and give pointers if you want to start a plugin for it.
